== Setup HTTPS for your blog

:title: Https for your blog
:category: security
:date: 17-09-2018
:tags: https,dns,ddos


There are multiple way to enable `https` for your site, and it's purely free of
cost. This is possible because of the community effort by `letsencrypt`.


I'm hosting my blog with `github pages`, so recently
github itself startered providing https certificates
for all github page sites.


If this isn't your option, another option is hosting your DNS with cloudflare.

Cloudflare got tone of advanced features for any type of websites. Most of
these fatures aren't usable for static blogs though, but we could make use
of the free certificates and http -> https redirect option along with the
DNS zone record hosting.



Does this really required to server the static and open content via `http` ?
    
It's highly recommended to follow the latest web standards. 
HTTP/2 is the the new version http which only works on TLS enabled mode.
This means enabling the https helps to ensure your site futurestic as well 
as protect against standard atacks.

Ddos Attack ?

All services are prone to this attack, but the service providers can detect
the DDOS early itself so that it can take actions like blocking connections
and etc. If you are hosting yur site on a well known servie providers like
Cloudera, Github, Godady, AWS etc, they already have mechanisms to mitigate
the DDOS attck.
